### ISSUE TITLE
StrokeBrush is not an AvaloniaProperty 

### ISSUE THREAD

**Issue by ProjetNice** [MarwanFr/LucideAvaloniaUI#1]
StrokeBrush is not an AvaloniaProperty ,This makes it impossible to change colors when switching themes

**Comment by MarwanFr** [comment]
Thank you for bringing this issue. I've resolved the problem you reported. A new version incorporating this fix will be released later today.

![image](https://github.com/MarwanFr/LucideAvaloniaUI/assets/155018178/f789a872-3519-4ff7-a6ce-2e472d34da9c)
