### ISSUE TITLE
Weird "points"

### ISSUE THREAD

**Issue by AWAS666** [MarwanFr/LucideAvaloniaUI#2]
The icons have these weird pointy things on the top left and bottom right when used
![image](https://github.com/user-attachments/assets/f2e9de14-4d43-4e60-998b-2bf195234705)

(using avalonia 11.1.3)

**Comment by MarwanFr** [comment]
The issue is caused by repetitive code that was added during the SVG to AXAML conversion (`M24,24z M0,0z`). This will be fixed on NuGet within 30 minutes.

**Comment by AWAS666** [comment]
Oh good to hear, thanks :)

**Comment by MarwanFr** [comment]
You're welcome, normally with version 1.6.1, it should be fixed. It is available [here](https://www.nuget.org/packages/LucideAvalonia/1.6.1).

**Comment by AWAS666** [comment]
> You're welcome, normally with version 1.6.1, it should be fixed. It is available [here](https://www.nuget.org/packages/LucideAvalonia/1.6.1).

yeah it's fixed now
